version: "3.8"

services:
  authapi:
    build: ./authAPI
    ports:
      - "9000:9000"
    networks:
      - social-network
    restart: always

  socialapi:
    build: ./socialAPI
    ports:
      - "3500:3500"
    depends_on:
      - authapi
    networks:
      - social-network
    restart: always

networks:
  social-network:
    driver: bridge
