version: '3.8'

services:
  aiohttp-regije:
    image: aiohttp-regije:1.0
    ports: 
      - "4000:4000"
    networks:
      - interna_mreza

  weather-fastapi:
    image: weather-fastapi:1.0
    ports:
      - "8000:8000"
    networks:
      - interna_mreza